import type { Metadata } from "next";
import "@/ui/globals.css";
import { extatica, goodTimes } from "@/ui/fonts";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(goodTimes.className, "overflow-hidden")}>
        {children}
      </body>
    </html>
  );
}
